author: narumi
name: RedstoneLimiter
version: 1.1
description: Better plugin for limiting redstone than RedstoneGuard xd
website: https://discord.gg/XWxPRHDfkK | https://github.com/narumii
main: uwu.narumi.Main